class AppLocalizationService {
  const AppLocalizationService._();

  static const supportedLanguages = [
    'English',
    'Spanish',
    'Mandarin Chinese',
    'Hindi',
    'Arabic',
    'French',
    'Bengali',
    'Portuguese',
    'Russian',
    'Urdu',
    'Indonesian',
    'German',
  ];

  static const _en = <String, String>{
    'appSettings': 'APP SETTINGS',
    'settingsDescription':
        'Persistent preferences live here. Gameplay controls stay inside the wheel.',
    'general': 'GENERAL',
    'gameplay': 'GAMEPLAY',
    'account': 'ACCOUNT',
    'legal': 'LEGAL',
    'soundEffects': 'Sound effects',
    'haptics': 'Haptics',
    'backgroundMusic': 'Background music',
    'reduceAnimations': 'Reduce animations',
    'enableDrinkingPrompts': 'Enable drinking prompts',
    'allowExtremePrompts': 'Allow extreme prompts',
    'language': 'Language',
    'appLanguage': 'APP LANGUAGE',
    'appLanguageDescription': 'Applies to the whole game interface.',
    'activeLanguage': 'Active language',
    'premium': 'Premium',
    'premiumStatus': 'Premium status',
    'lifetimeUnlocked': 'Lifetime unlocked',
    'freePlan': 'Free plan',
    'rateApp': 'Rate app',
    'resetStatistics': 'Reset statistics',
    'clearsLocalGameData': 'Clears local game data',
    'appDataReset': 'App data reset.',
    'privacyPolicy': 'Privacy policy',
    'privacyPolicyTitle': 'Privacy Policy',
    'privacyPolicyBody':
        'Chaos Wheel stores local game preferences and premium entitlement on this device. No account data is collected in this build.',
    'terms': 'Terms',
    'termsBody':
        'Chaos Wheel is a social party game. Players are responsible for consent, comfort, and stopping any prompt that does not fit the room.',
    'version': 'Version',
    'versionBody': 'Chaos Wheel 0.1.0',
    'ok': 'OK',
    'storeOpenFailed': 'Could not open the store page.',
    'startGame': 'START GAME',
    'startGameSubtitle': 'Spin the wheel of fate',
    'howToPlay': 'How to Play',
    'rulesOfChaos': 'Rules of chaos',
    'unlockChaosMode': 'Unlock chaos mode',
    'homeTagline': 'TRUTH  .  DARE  .  DRINK  .  NO ESCAPE',
    'whoIsPlaying': "Who's playing\ntonight?",
    'addPlayersHelper':
        'Add at least 2 players. No duplicates. The wheel decides everything.',
    'noPlayersYet': 'No players yet. Add the chaos crew below',
    'addPlayerName': 'Add player name...',
    'startPlayers': 'START - {count} PLAYERS ->',
    'addOneMorePlayer': 'ADD 1 MORE PLAYER',
    'addMorePlayers': 'ADD {count} MORE PLAYERS',
    'chooseYourPoison': 'Choose your\npoison.',
    'howChaoticTonight': 'How chaotic will tonight become?',
    'vibe': 'VIBE',
    'cozy': 'COZY',
    'spicy': 'SPICY',
    'unhinged': 'UNHINGED',
    'evil': 'EVIL',
    'cozyDesc': 'Safe, funny, low-pressure chaos',
    'spicyDesc': 'Flirty tension & risky confessions',
    'unhingedDesc': 'Late-night social destruction',
    'evilDesc': 'Friendship-ending chaos',
    'currentVibe': 'CURRENT VIBE',
    'cozySummary': 'social pressure stays playful',
    'spicySummary': 'flirty tension is active',
    'unhingedSummary': 'exposure risk is high',
    'evilSummary': 'premium danger is armed',
    'gameMode': 'GAME MODE',
    'quickChaos': 'QUICK CHAOS',
    'partyChaos': 'PARTY CHAOS',
    'totalChaos': 'TOTAL CHAOS',
    'customGame': 'CUSTOM GAME',
    'customGameDesc': 'Set rounds, shots and targets',
    'premiumHouseRules': 'Premium house rules',
    'playersShotsTargets':
        '{players} players - {shots} shots - {targets} target',
    'playersShotsTargetsPlural':
        '{players} players - {shots} shots - {targets} targets',
    'noEscapeActivates': 'NO ESCAPE ACTIVATES',
    'inRound': 'IN ROUND {round}',
    'shotsTargetsLocked': 'Shots and targets become locked.',
    'perPlayerRights': 'PER-PLAYER RIGHTS',
    'shots': 'SHOTS',
    'targets': 'TARGETS',
    'perPlayer': 'per player',
    'redirectEach': 'redirect each',
    'advancedChaosSettings': 'Advanced Chaos Settings',
    'modifiersLocksPremiumChaos': 'Modifiers, locks and premium chaos.',
    'balanceRule': 'Balance Rule',
    'balanceRuleDesc': 'Lock Truth only after 2 Truths in a row',
    'randomButton': 'Random Button',
    'randomButtonDesc': 'Let fate decide truth or dare',
    'startChaos': 'START {vibe}',
    'startCustomGame': 'START CUSTOM GAME',
    'startChaosMeta':
        '{rounds} ROUNDS - {players} PLAYERS - NO ESCAPE R{round}',
    'rounds': 'ROUNDS',
    'chooseYourFate': 'CHOOSE\nYOUR FATE',
    'step1of2': 'STEP 1 / 2',
    'noEscapeMode': 'NO ESCAPE MODE',
    'yourChoiceYourChaos': '{player}, your choice. Your chaos.',
    'truth': 'TRUTH',
    'dare': 'DARE',
    'random': 'RANDOM',
    'lockedThisTurn': 'Locked this turn.',
    'tellTheTruth': 'Tell the truth.',
    'takeTheRisk': 'Take the risk.',
    'letChaosDecide': 'Let chaos decide.',
    'shotTargetLockedRandomLeansDare':
        'SHOT + TARGET LOCKED - RANDOM LEANS DARE',
    'gameControls': 'GAME CONTROLS',
    'gameControlsSubtitle':
        'Quick fixes for the current chaos session. App settings stay on Home.',
    'round': 'ROUND',
    'players': 'PLAYERS',
    'session': 'SESSION',
    'safety': 'SAFETY',
    'skipRound': 'Skip round',
    'skipRoundDesc': 'End this round without a challenge',
    'respinWheel': 'Respin wheel',
    'respinWheelDesc': 'Clear the current pick and spin again',
    'randomizePicker': 'Randomize picker',
    'randomizePickerDesc': 'Pick someone instantly',
    'addPlayer': 'Add player',
    'addPlayerDesc': 'Bring someone into the chaos',
    'removePlayer': 'Remove player',
    'removePlayerDesc': 'Choose who leaves this session',
    'pauseGame': 'Pause game',
    'resumeGame': 'Resume game',
    'pauseGameDesc': 'Freeze wheel actions for a break',
    'endGame': 'End game',
    'endGameDesc': 'Jump to the Chaos Report',
    'toneDownPrompts': 'Tone down prompts',
    'toneDownPromptsDesc': 'Reduce prompt intensity for this session',
    'disableDrinkingPrompts': 'Disable drinking prompts',
    'disableDrinkingPromptsDesc': 'Remove shot/drinking prompts now',
    'soundEffectsOn': 'Sound effects on',
    'soundEffectsOff': 'Sound effects off',
    'toggleGameplaySfx': 'Toggle gameplay sound effects',
    'tapSpinToDraw': 'TAP SPIN TO DRAW',
    'finalSpin': 'FINAL SPIN',
    'whosNext': "Who's next?",
    'spin': 'SPIN',
    'chooseFate': 'CHOOSE FATE',
    'truthSelected': 'Truth selected.',
    'dareSelected': 'Dare selected.',
    'youGotTargeted': 'You got targeted.',
    'willYouTellIt': '{player}, will you tell it?',
    'willYouDoIt': '{player}, will you do it?',
    'handleThisTruth': 'Handle this truth.',
    'handleThisDare': 'Handle this dare.',
    'tellIt': 'TELL IT',
    'sendIt': 'SEND IT',
    'changeQuestion': 'Change Question',
    'changeDare': 'Change Dare',
    'noChangesLeft': 'No changes left',
    'left': 'left',
    'shot': 'Shot',
    'target': 'Target',
    'noShotsLeft': 'No shots left',
    'spinTheWheel': 'Spin the wheel...',
    'question': 'Question',
    'theRoomIsWatching': 'The room is watching.',
    'chaosDemandsSacrifice': 'Chaos demands sacrifice.',
    'nextTurn': 'NEXT TURN',
    'seeResults': 'SEE RESULTS',
    'gameComplete': 'GAME COMPLETE',
    'nextUpRound': 'NEXT UP - ROUND {round} / {total}',
    'shotTaken': 'SHOT TAKEN',
    'spendsOneShotToken': '{player} spends one shot token.',
    'targeted': 'TARGETED',
    'gotTargetedBy': '{target} got targeted by {source}.',
    'revengeAvailable': 'REVENGE AVAILABLE',
    'revengeActivated': 'REVENGE ACTIVATED',
    'letItGo': 'LET IT GO',
    'noEscape': 'NO ESCAPE',
    'noEscapeBody': 'Shots and targets are locked. Survive the final rounds.',
    'wheelHasSpoken': 'THE WHEEL HAS SPOKEN',
    'isPicked': 'is picked.',
    'chaosReport': 'CHAOS\nREPORT',
    'wheelKeptReceipts': 'The wheel kept receipts.',
    'mvp': 'MVP',
    'mostPicked': 'Most picked',
    'biggestEscaper': 'Biggest Escaper',
    'mostShotsUsed': 'Most shots used',
    'sniper': 'Sniper',
    'mostTargetsUsed': 'Most targets used',
    'mostHated': 'Most Hated',
    'mostTargeted': 'Most targeted',
    'fearless': 'Fearless',
    'leastShotsUsed': 'Least shots used',
    'dareDevil': 'Dare Devil',
    'mostDares': 'Most dares',
    'honestSoul': 'Honest Soul',
    'mostTruths': 'Most truths',
    'suspiciouslySafe': 'Suspiciously Safe',
    'truthHeavy': 'Truth-heavy',
    'shareTheChaos': 'SHARE THE CHAOS',
    'playAgain': 'PLAY AGAIN',
    'newGame': 'NEW GAME',
    'howChaosWorks': 'How Chaos Works',
    'howChaosIntro':
        'Spin the wheel, get picked, face the prompt, or spend your shot.',
    'howChaosSubtitle': 'The app runs the questions, dares and final pressure.',
    'flow': 'FLOW',
    'specialRules': 'SPECIAL RULES',
    'vibes': 'VIBES',
    'addPlayers': 'ADD PLAYERS',
    'addPlayersRule': 'Add everyone in the room before the game starts.',
    'pickYourVibe': 'PICK YOUR VIBE',
    'pickYourVibeRule':
        'Cozy is safe, Spicy is flirty, Unhinged is chaotic, Evil is premium.',
    'spinTheWheelRule': 'The wheel chooses who faces the next prompt.',
    'truthOrDare': 'TRUTH OR DARE',
    'truthOrDareRule': 'The app gives the question or task automatically.',
    'targetRule': 'Redirects the challenge to another player.',
    'shotRule': 'Use a shot token to skip.',
    'noEscapeRule': 'In final rounds, shots and targets are locked.',
    'cozyVibeRule': 'Funny and safe chaos.',
    'spicyVibeRule': 'Flirty tension and risky confessions.',
    'unhingedVibeRule': 'Social destruction and dangerous choices.',
    'evilVibeRule': 'Friendship-ending premium chaos.',
    'chooseTarget': 'Choose\na target.',
    'noActivePlayer': 'No active player selected.',
    'redirectingChallenge': '{player} is redirecting this challenge.',
    'sameChallengePassed':
        'The same question or dare will be passed to the target.',
  };

  static const _es = <String, String>{
    'appSettings': 'AJUSTES',
    'settingsDescription':
        'Las preferencias viven aqui. Los controles de partida estan dentro de la ruleta.',
    'general': 'GENERAL',
    'gameplay': 'JUEGO',
    'account': 'CUENTA',
    'legal': 'LEGAL',
    'soundEffects': 'Efectos de sonido',
    'haptics': 'Vibracion',
    'backgroundMusic': 'Musica de fondo',
    'reduceAnimations': 'Reducir animaciones',
    'enableDrinkingPrompts': 'Activar retos de shot',
    'allowExtremePrompts': 'Permitir retos extremos',
    'language': 'Idioma',
    'appLanguage': 'IDIOMA',
    'appLanguageDescription': 'Se aplica a toda la interfaz del juego.',
    'activeLanguage': 'Idioma activo',
    'premiumStatus': 'Estado Premium',
    'lifetimeUnlocked': 'Desbloqueado de por vida',
    'freePlan': 'Plan gratis',
    'rateApp': 'Valorar app',
    'resetStatistics': 'Reiniciar estadisticas',
    'clearsLocalGameData': 'Borra datos locales del juego',
    'appDataReset': 'Datos reiniciados.',
    'privacyPolicy': 'Politica de privacidad',
    'privacyPolicyTitle': 'Politica de Privacidad',
    'privacyPolicyBody':
        'Chaos Wheel guarda preferencias locales y el estado Premium en este dispositivo. Esta version no recopila datos de cuenta.',
    'terms': 'Terminos',
    'termsBody':
        'Chaos Wheel es un juego social. Los jugadores son responsables del consentimiento, comodidad y de parar cualquier reto que no encaje.',
    'version': 'Version',
    'versionBody': 'Chaos Wheel 0.1.0',
    'ok': 'OK',
    'storeOpenFailed': 'No se pudo abrir la tienda.',
    'startGame': 'EMPEZAR',
    'startGameSubtitle': 'Gira la ruleta del destino',
    'howToPlay': 'Como jugar',
    'rulesOfChaos': 'Reglas del caos',
    'premium': 'Premium',
    'unlockChaosMode': 'Desbloquea modo caos',
    'homeTagline': 'VERDAD  .  RETO  .  SHOT  .  SIN ESCAPE',
    'whoIsPlaying': 'Quien juega\nesta noche?',
    'addPlayersHelper':
        'Agrega al menos 2 jugadores. Sin duplicados. La ruleta decide todo.',
    'noPlayersYet': 'Aun no hay jugadores. Agrega el crew abajo',
    'addPlayerName': 'Nombre del jugador...',
    'startPlayers': 'EMPEZAR - {count} JUGADORES ->',
    'addOneMorePlayer': 'AGREGA 1 JUGADOR MAS',
    'addMorePlayers': 'AGREGA {count} JUGADORES MAS',
    'chooseYourPoison': 'Elige tu\nveneno.',
    'howChaoticTonight': 'Que tan caotica sera la noche?',
    'vibe': 'VIBRA',
    'cozy': 'SUAVE',
    'spicy': 'PICANTE',
    'unhinged': 'DESATADO',
    'evil': 'MALVADO',
    'cozyDesc': 'Caos seguro, divertido y sin presion',
    'spicyDesc': 'Tension coqueta y confesiones riesgosas',
    'unhingedDesc': 'Destruccion social de madrugada',
    'evilDesc': 'Caos que rompe amistades',
    'currentVibe': 'VIBRA ACTUAL',
    'cozySummary': 'la presion social sigue divertida',
    'spicySummary': 'la tension coqueta esta activa',
    'unhingedSummary': 'el riesgo de exposicion es alto',
    'evilSummary': 'peligro premium activado',
    'gameMode': 'MODO',
    'quickChaos': 'CAOS RAPIDO',
    'partyChaos': 'CAOS PARTY',
    'totalChaos': 'CAOS TOTAL',
    'customGame': 'JUEGO CUSTOM',
    'customGameDesc': 'Configura rondas, shots y targets',
    'premiumHouseRules': 'Reglas premium',
    'playersShotsTargets':
        '{players} jugadores - {shots} shots - {targets} target',
    'playersShotsTargetsPlural':
        '{players} jugadores - {shots} shots - {targets} targets',
    'noEscapeActivates': 'SIN ESCAPE SE ACTIVA',
    'inRound': 'EN RONDA {round}',
    'shotsTargetsLocked': 'Shots y targets se bloquean.',
    'perPlayerRights': 'DERECHOS POR JUGADOR',
    'shots': 'SHOTS',
    'targets': 'TARGETS',
    'perPlayer': 'por jugador',
    'redirectEach': 'redirigir cada uno',
    'advancedChaosSettings': 'Ajustes avanzados de caos',
    'modifiersLocksPremiumChaos': 'Modificadores, bloqueos y caos premium.',
    'balanceRule': 'Regla de balance',
    'balanceRuleDesc': 'Bloquea Verdad solo tras 2 Verdades seguidas',
    'randomButton': 'Boton Random',
    'randomButtonDesc': 'Deja que el destino elija verdad o reto',
    'startChaos': 'EMPEZAR {vibe}',
    'startCustomGame': 'EMPEZAR CUSTOM',
    'startChaosMeta':
        '{rounds} RONDAS - {players} JUGADORES - SIN ESCAPE R{round}',
    'rounds': 'RONDAS',
    'chooseYourFate': 'ELIGE\nTU DESTINO',
    'step1of2': 'PASO 1 / 2',
    'noEscapeMode': 'MODO SIN ESCAPE',
    'yourChoiceYourChaos': '{player}, tu eleccion. Tu caos.',
    'truth': 'VERDAD',
    'dare': 'RETO',
    'random': 'RANDOM',
    'lockedThisTurn': 'Bloqueado este turno.',
    'tellTheTruth': 'Di la verdad.',
    'takeTheRisk': 'Toma el riesgo.',
    'letChaosDecide': 'Que decida el caos.',
    'shotTargetLockedRandomLeansDare':
        'SHOT + TARGET BLOQUEADOS - RANDOM TIRA A RETO',
    'gameControls': 'CONTROLES',
    'gameControlsSubtitle':
        'Arreglos rapidos para esta partida. Los ajustes quedan en Inicio.',
    'round': 'RONDA',
    'players': 'JUGADORES',
    'session': 'SESION',
    'safety': 'SEGURIDAD',
    'skipRound': 'Saltar ronda',
    'skipRoundDesc': 'Termina esta ronda sin reto',
    'respinWheel': 'Girar de nuevo',
    'respinWheelDesc': 'Borra la eleccion actual y gira otra vez',
    'randomizePicker': 'Elegir al azar',
    'randomizePickerDesc': 'Elige a alguien al instante',
    'addPlayer': 'Agregar jugador',
    'addPlayerDesc': 'Mete a alguien al caos',
    'removePlayer': 'Quitar jugador',
    'removePlayerDesc': 'Elige quien sale de la sesion',
    'pauseGame': 'Pausar juego',
    'resumeGame': 'Reanudar juego',
    'pauseGameDesc': 'Congela la ruleta para un descanso',
    'endGame': 'Terminar juego',
    'endGameDesc': 'Ir al Reporte de Caos',
    'toneDownPrompts': 'Bajar intensidad',
    'toneDownPromptsDesc': 'Reduce la intensidad de retos',
    'disableDrinkingPrompts': 'Desactivar shots',
    'disableDrinkingPromptsDesc': 'Quita retos de shot ahora',
    'soundEffectsOn': 'Sonido activado',
    'soundEffectsOff': 'Sonido apagado',
    'toggleGameplaySfx': 'Activar/desactivar sonido del juego',
    'tapSpinToDraw': 'TOCA SPIN PARA ELEGIR',
    'finalSpin': 'GIRO FINAL',
    'whosNext': 'Quien sigue?',
    'spin': 'SPIN',
    'chooseFate': 'ELIGE DESTINO',
    'truthSelected': 'Verdad elegida.',
    'dareSelected': 'Reto elegido.',
    'youGotTargeted': 'Te hicieron target.',
    'willYouTellIt': '{player}, lo diras?',
    'willYouDoIt': '{player}, lo haras?',
    'handleThisTruth': 'Enfrenta esta verdad.',
    'handleThisDare': 'Enfrenta este reto.',
    'tellIt': 'DILO',
    'sendIt': 'HAZLO',
    'changeQuestion': 'Cambiar pregunta',
    'changeDare': 'Cambiar reto',
    'noChangesLeft': 'Sin cambios',
    'left': 'restante',
    'shot': 'Shot',
    'target': 'Target',
    'noShotsLeft': 'Sin shots',
    'spinTheWheel': 'Gira la ruleta...',
    'question': 'Pregunta',
    'theRoomIsWatching': 'La sala esta mirando.',
    'chaosDemandsSacrifice': 'El caos exige sacrificio.',
    'nextTurn': 'SIGUIENTE TURNO',
    'seeResults': 'VER RESULTADOS',
    'gameComplete': 'JUEGO COMPLETO',
    'nextUpRound': 'SIGUE - RONDA {round} / {total}',
    'shotTaken': 'SHOT USADO',
    'spendsOneShotToken': '{player} gasta un token de shot.',
    'targeted': 'TARGETED',
    'gotTargetedBy': '{target} fue target de {source}.',
    'revengeAvailable': 'REVANCHA DISPONIBLE',
    'revengeActivated': 'REVANCHA ACTIVADA',
    'letItGo': 'DEJARLO PASAR',
    'noEscape': 'SIN ESCAPE',
    'noEscapeBody':
        'Shots y targets estan bloqueados. Sobrevive las rondas finales.',
    'wheelHasSpoken': 'LA RULETA HA HABLADO',
    'isPicked': 'fue elegido.',
    'chaosReport': 'REPORTE\nDE CAOS',
    'wheelKeptReceipts': 'La ruleta guardo pruebas.',
    'mvp': 'MVP',
    'mostPicked': 'Mas elegido',
    'biggestEscaper': 'Mayor escapista',
    'mostShotsUsed': 'Mas shots usados',
    'sniper': 'Sniper',
    'mostTargetsUsed': 'Mas targets usados',
    'mostHated': 'Mas odiado',
    'mostTargeted': 'Mas targeteado',
    'fearless': 'Valiente',
    'leastShotsUsed': 'Menos shots usados',
    'dareDevil': 'Dare Devil',
    'mostDares': 'Mas retos',
    'honestSoul': 'Alma honesta',
    'mostTruths': 'Mas verdades',
    'suspiciouslySafe': 'Sospechosamente seguro',
    'truthHeavy': 'Muchas verdades',
    'shareTheChaos': 'COMPARTIR CAOS',
    'playAgain': 'JUGAR OTRA VEZ',
    'newGame': 'NUEVO JUEGO',
    'howChaosWorks': 'Como funciona el caos',
    'howChaosIntro':
        'Gira la ruleta, sal elegido, enfrenta la pregunta o gasta tu shot.',
    'howChaosSubtitle': 'La app controla preguntas, retos y la presion final.',
    'flow': 'FLUJO',
    'specialRules': 'REGLAS ESPECIALES',
    'vibes': 'VIBRAS',
    'addPlayers': 'AGREGA JUGADORES',
    'addPlayersRule': 'Agrega a todos antes de empezar.',
    'pickYourVibe': 'ELIGE TU VIBRA',
    'pickYourVibeRule':
        'Suave es seguro, Picante coquetea, Desatado es caos, Malvado es premium.',
    'spinTheWheelRule': 'La ruleta elige quien enfrenta el reto.',
    'truthOrDare': 'VERDAD O RETO',
    'truthOrDareRule': 'La app da la pregunta o tarea automaticamente.',
    'targetRule': 'Redirige el reto a otro jugador.',
    'shotRule': 'Usa un token de shot para saltar.',
    'noEscapeRule': 'En las rondas finales, shots y targets se bloquean.',
    'cozyVibeRule': 'Caos divertido y seguro.',
    'spicyVibeRule': 'Tension coqueta y confesiones riesgosas.',
    'unhingedVibeRule': 'Destruccion social y decisiones peligrosas.',
    'evilVibeRule': 'Caos premium que rompe amistades.',
    'chooseTarget': 'Elige\nun target.',
    'noActivePlayer': 'No hay jugador activo.',
    'redirectingChallenge': '{player} esta redirigiendo este reto.',
    'sameChallengePassed': 'La misma pregunta o reto pasara al target.',
  };

  static const _core = <String, Map<String, String>>{
    'French': {
      'startGame': 'COMMENCER',
      'howToPlay': 'Comment jouer',
      'premium': 'Premium',
      'language': 'Langue',
      'appSettings': 'REGLAGES',
      'truth': 'VERITE',
      'dare': 'DEFI',
      'random': 'HASARD',
      'spin': 'SPIN',
      'nextTurn': 'TOUR SUIVANT',
      'noEscape': 'SANS ISSUE',
    },
    'Portuguese': {
      'startGame': 'COMEÇAR',
      'howToPlay': 'Como jogar',
      'premium': 'Premium',
      'language': 'Idioma',
      'appSettings': 'CONFIGURAÇÕES',
      'truth': 'VERDADE',
      'dare': 'DESAFIO',
      'random': 'ALEATORIO',
      'spin': 'SPIN',
      'nextTurn': 'PROXIMA VEZ',
      'noEscape': 'SEM ESCAPE',
    },
    'German': {
      'startGame': 'STARTEN',
      'howToPlay': 'Spielanleitung',
      'premium': 'Premium',
      'language': 'Sprache',
      'appSettings': 'APP-EINSTELLUNGEN',
      'truth': 'WAHRHEIT',
      'dare': 'MUTPROBE',
      'random': 'ZUFALL',
      'spin': 'SPIN',
      'nextTurn': 'NACHSTE RUNDE',
      'noEscape': 'KEIN ENTKOMMEN',
    },
  };

  static String text(String key, String language) {
    final localized = switch (language) {
      'Spanish' => _es[key],
      'English' => _en[key],
      _ => _core[language]?[key],
    };
    return localized ?? _en[key] ?? key;
  }

  static String format(
    String key,
    String language,
    Map<String, Object> values,
  ) {
    var result = text(key, language);
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return result;
  }
}
