// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlANyrYz03R6bnp9a1nj4JCbXFeJVFFCQ',
    appId: '1:845159211048:web:89fefe087fc3f7012ed51d',
    messagingSenderId: '845159211048',
    projectId: 'chaos-wheel-party-game',
    authDomain: 'chaos-wheel-party-game.firebaseapp.com',
    storageBucket: 'chaos-wheel-party-game.firebasestorage.app',
    measurementId: 'G-W4BB36SWYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsbFdnl4JMifcc_Y9dGGXRSi651q5unc',
    appId: '1:845159211048:android:d82c0f62f9ecbe772ed51d',
    messagingSenderId: '845159211048',
    projectId: 'chaos-wheel-party-game',
    storageBucket: 'chaos-wheel-party-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9IEksAgNetc-lAuczEh0xhuNpf5jZVA',
    appId: '1:845159211048:ios:85dc4d4d776ced312ed51d',
    messagingSenderId: '845159211048',
    projectId: 'chaos-wheel-party-game',
    storageBucket: 'chaos-wheel-party-game.firebasestorage.app',
    iosBundleId: 'com.skyroonlabs.chaoswheel',
  );
}
